export const products = [
    {
        coverimg: '../assets/img/240_F_185086879_iXrZ34IniEE74SHMGT9SIhCfUbq3KDjs.jpg',
        hcoverimg1: '../assets/img/240_F_664405322_ktxfhLp5vJYbQQYFqN7EbingtQcOpM9d.jpg',
        hcoverimg2: '../assets/img/240_F_318373695_ZMns3h5OSI8ddJu1Dd1QmFhSP8CMvSVK.jpg',
        hcoverimg3: '../assets/img/240_F_317004103_QPOn9rd0rGc6W0aWQswSNNKNznF1dv2u.jpg',
        name: '齋藤　翔太',
        gender: '男性',
        age: '8歳',
        heading1: '南本町小学校４年生',
        heading2: '🏀バスケットボール',
        heading3: '長男',
        headingtext1: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
        headingtext3: 'Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.',
    },
    {
        coverimg: ' ',
        hcoverimg1: '../assets/img/240_F_664405322_ktxfhLp5vJYbQQYFqN7EbingtQcOpM9d.jpg',
        hcoverimg2: '../assets/img/240_F_318373695_ZMns3h5OSI8ddJu1Dd1QmFhSP8CMvSVK.jpg',
        hcoverimg3: '../assets/img/240_F_317004103_QPOn9rd0rGc6W0aWQswSNNKNznF1dv2u.jpg',
        name: '齋藤　陽七太',
        gender: '男性',
        age: '4歳',
        heading1: '🌱二葉幼稚園年中組',
        heading2: 'トミカ・プラレール',
        heading3: '次男',
        headingtext1: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
        headingtext3: 'Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.',
    },
    {
        coverimg: ' ',
        hcoverimg1: '../assets/img/240_F_664405322_ktxfhLp5vJYbQQYFqN7EbingtQcOpM9d.jpg',
        hcoverimg2: '../assets/img/240_F_318373695_ZMns3h5OSI8ddJu1Dd1QmFhSP8CMvSVK.jpg',
        hcoverimg3: '../assets/img/240_F_317004103_QPOn9rd0rGc6W0aWQswSNNKNznF1dv2u.jpg',
        name: '齋藤　梓',
        gender: '女性',
        age: '44歳',
        heading1: '👩齋藤家お母さん',
        heading2: 'お茶会・ショッピング',
        heading3: '母',
        headingtext1: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
        headingtext3: 'Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.',
    },
    {
        coverimg: ' ',
        hcoverimg1: '../assets/img/240_F_664405322_ktxfhLp5vJYbQQYFqN7EbingtQcOpM9d.jpg',
        hcoverimg2: '../assets/img/240_F_318373695_ZMns3h5OSI8ddJu1Dd1QmFhSP8CMvSVK.jpg',
        hcoverimg3: '../assets/img/240_F_317004103_QPOn9rd0rGc6W0aWQswSNNKNznF1dv2u.jpg',
        name: '齋藤　英朗',
        gender: '男性',
        age: '53歳',
        heading1: '👨齋藤家お父さん',
        heading2: '⛳️ゴルフ',
        heading3: '父',
        headingtext1: 'Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.',
        headingtext2: 'Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.',
        headingtext3: 'Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.',
    }
];